### ISSUE TITLE
<enhancement> Mount local directories to start with defined prefs 

### ISSUE THREAD

**Issue by railfox** [PauloASilva/TomTomSportsConnect#2]
Hi Paulo,

thank you for your work.

I've added the following directory mounts to the docker run -  command:

    -v /home/mylocaluser/TomTom\ Sports:/root/TomTom\ Sports \
    -v /home/mylocaluser/.local/share/TomTom/:/root/.local/share/TomTom/ \

With this you don't have to confirm license and other stuff on every container startup 
- you will keep your preferences.
On the other hand you need this if you want to get a local copy of your data (tcx-files).

Best regards,
Martin

**Comment by PauloASilva** [comment]
Hey @railfox,
Thanks for your contribution.

I remember to have tested something similar but without success: I was using `~/.config` instead of `~/.local`.

I think that, replacing `/home/mylocaluser` by `"$HOME"` it will work at least for all linux distributions.
Then we should test Mac OS and write a `.bat` file for Windows.

Would you like to open the Pull Request?

Cheers,
Paulo A. Silva

**Comment by railfox** [comment]
Hi Paulo,
pull request done.

Regards,
Martin

PS: Do you think that this will be widely used from MAc & Win? There are official supported packages for both OS by TT itself.

**Comment by PauloASilva** [comment]
Hi @railfox,
You're right: linux is our target.

Cheers,
Paulo A. Silva
